backend:
  name: github
  repo: NilayKurt/mtmessestandweb
  branch: master
  base_url: https://nilaykurt.github.io/mtmessestandweb
  auth_endpoint: https://github.com/login/oauth/authorize
  client_id: Ov23lis8Tc4RDzLT8fK6

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["Comparison", "Guide", "Case Study", "Trends"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["Wooden", "Octanorm", "Maxima", "Truss", "Pavilion"]}

  - name: "faq"
    label: "FAQ"
    folder: "faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}
      - {label: "Category", name: "category", widget: "select", options: ["Cost", "Process", "Technical"]}
