<?php
// admin/actions/upload.php — Media upload with full SEO pipeline
try {
    require_once __DIR__ . '/../auth.php';
    require_login();
    check_csrf();

    if (!isset($_FILES['image']) || $_FILES['image']['error'] !== UPLOAD_ERR_OK) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('Yükleme hatası'));
        exit;
    }

    $file = $_FILES['image'];
    if ($file['size'] > 5 * 1024 * 1024) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('Dosya 5MB\'dan büyük'));
        exit;
    }

    $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    if (!in_array($ext, ['webp', 'jpg', 'jpeg', 'png'])) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('Geçersiz dosya türü'));
        exit;
    }

    $finfo = finfo_open(FILEINFO_MIME_TYPE);
    $mime = finfo_file($finfo, $file['tmp_name']);
    finfo_close($finfo);
    if (!in_array($mime, ['image/webp', 'image/jpeg', 'image/png'])) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('Geçersiz MIME türü'));
        exit;
    }

    // AI marker scan
    $ai_markers = ['midjourney', 'dalle', 'dall-e', 'stable-diffusion', 'synthetic',
                   'ai-generated', 'generated by ai', 'imagen', 'adobe firefly',
                   'created with ai', 'ai_gen'];
    $fname_lower = strtolower($file['name']);
    $raw_head = file_get_contents($file['tmp_name'], false, null, 0, 8192);
    $ai_detected = false;
    foreach ($ai_markers as $marker) {
        $clean = str_replace([' ', '-'], '', $marker);
        if (strpos(str_replace(['-', '_'], '', $fname_lower), $clean) !== false) { $ai_detected = true; break; }
        if (stripos($raw_head, $clean) !== false) { $ai_detected = true; break; }
    }
    if ($ai_detected) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('AI üretimi görsel tespit edildi'));
        exit;
    }

    // Open source image (EXIF auto-stripped by GD)
    if ($mime === 'image/png') {
        $src_img = imagecreatefrompng($file['tmp_name']);
    } elseif ($mime === 'image/webp') {
        $src_img = imagecreatefromwebp($file['tmp_name']);
    } else {
        $src_img = imagecreatefromjpeg($file['tmp_name']);
    }
    if (!$src_img) {
        $redirect = $_POST['redirect'] ?? '../media.php';
        header('Location: ' . $redirect . '?error=' . urlencode('Bozuk görsel'));
        exit;
    }

    // Resize to 1200px wide if larger
    $orig_w = imagesx($src_img);
    $orig_h = imagesy($src_img);
    if ($orig_w > 1200) {
        $target_w = 1200;
        $target_h = (int)($orig_h * $target_w / $orig_w);
        $resized = imagecreatetruecolor($target_w, $target_h);
        imagecopyresampled($resized, $src_img, 0, 0, 0, 0, $target_w, $target_h, $orig_w, $orig_h);
        imagedestroy($src_img);
        $src_img = $resized;
    }

    // SEO filename — Turkish chars to ASCII
    $raw_name = $_POST['filename'] ?? pathinfo($file['name'], PATHINFO_FILENAME);
    $safe_name = str_replace(
        ['ı','İ','ş','Ş','ğ','Ğ','ü','Ü','ö','Ö','ç','Ç'],
        ['i','i','s','s','g','g','u','u','o','o','c','c'],
        $raw_name
    );
    $safe_name = trim(preg_replace('/[^a-zA-Z0-9]+/', '-', $safe_name), '-');
    $safe_name = strtolower($safe_name) ?: 'image';
    $filename = $safe_name . '.webp';

    // Target directory
    $target_dir = $_POST['target'] ?? 'blog';
    if (!in_array($target_dir, ['blog', 'portfolio', 'about'])) {
        $target_dir = 'blog';
    }
    $upload_dir = __DIR__ . '/../../assets/img/' . $target_dir;
    if (!is_dir($upload_dir)) mkdir($upload_dir, 0755, true);

    // Prevent duplicate
    $counter = 1;
    $base = $safe_name;
    while (file_exists("$upload_dir/$filename")) {
        $filename = $base . '-' . $counter . '.webp';
        $counter++;
    }
    $target = "$upload_dir/$filename";

    // Watermark
    $logo_path = __DIR__ . '/../../assets/img/logo.webp';
    if (file_exists($logo_path)) {
        $logo = imagecreatefromwebp($logo_path);
        if ($logo) {
            $lw = imagesx($logo); $lh = imagesy($logo);
            $iw = imagesx($src_img); $ih = imagesy($src_img);
            imagecopymerge($src_img, $logo, $iw - $lw - 20, $ih - $lh - 20, 0, 0, $lw, $lh, 30);
            imagedestroy($logo);
        }
    }

    // Save WEBP
    imagewebp($src_img, $target, 85);
    $final_w = imagesx($src_img);
    $final_h = imagesy($src_img);
    imagedestroy($src_img);

    // XMP metadata
    $year = date('Y');
    @exec(sprintf(
        'exiftool -overwrite_original -q ' .
        '-XMP-dc:Creator="MT Messe Stand" ' .
        '-XMP-dc:Rights="© %s MT Messe Stand. All rights reserved." ' .
        '-XMP-dc:Title="%s" ' .
        '-XMP-dc:Subject="exhibition stand, trade fair" ' .
        '%s 2>/dev/null',
        escapeshellarg($year),
        escapeshellarg($safe_name),
        escapeshellarg($target)
    ));

    // Steganography
    $copyright = '© MT Messe Stand ' . $year;
    $img = imagecreatefromwebp($target);
    $w = imagesx($img);
    for ($i = 0; $i < min(strlen($copyright), $w); $i++) {
        $rgb = imagecolorat($img, $i, 0);
        $r = ($rgb >> 16) & 0xFF; $g = ($rgb >> 8) & 0xFF; $b = $rgb & 0xFF;
        $char = ord($copyright[$i]);
        $r = ($r & 0xFC) | (($char >> 6) & 0x03);
        $g = ($g & 0xFC) | (($char >> 4) & 0x03);
        $b = ($b & 0xFC) | (($char >> 2) & 0x03);
        imagesetpixel($img, $i, 0, imagecolorallocate($img, $r, $g, $b));
    }
    imagewebp($img, $target, 85);
    imagedestroy($img);

    // Check if this is an inline editor upload (return JSON with URL)
    $is_inline = !empty($_POST['inline']);
    if ($is_inline) {
        $img_url = '/assets/img/' . $target_dir . '/' . $filename;
        header('Content-Type: application/json');
        echo json_encode(['success' => true, 'url' => $img_url, 'width' => $final_w, 'height' => $final_h]);
        exit;
    }

    log_action('upload', 'success', ['file' => $filename, 'dir' => $target_dir]);
    $redirect = $_POST['redirect'] ?? '../media.php';
    header('Location: ' . $redirect . '?uploaded=1');

} catch (Throwable $e) {
    log_error('Upload: ' . $e->getMessage());
    $redirect = $_POST['redirect'] ?? '../media.php';
    header('Location: ' . $redirect . '?error=' . urlencode('Sistem hatası'));
}
