<?php
// admin/actions/upload-reference.php — Full processing pipeline
try {
    require_once __DIR__ . '/../auth.php';
    require_login();
    check_csrf();

    // ── 1. Validate upload ──
    if (!isset($_FILES['image']) || $_FILES['image']['error'] !== UPLOAD_ERR_OK) {
        header('Location: ../editor-references.php?error=upload_failed');
        exit;
    }
    $file = $_FILES['image'];
    if ($file['size'] > 5 * 1024 * 1024) {
        header('Location: ../editor-references.php?error=too_large');
        exit;
    }
    $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    if (!in_array($ext, ['jpg', 'jpeg', 'png'])) {
        header('Location: ../editor-references.php?error=invalid_type');
        exit;
    }
    $finfo = finfo_open(FILEINFO_MIME_TYPE);
    $mime = finfo_file($finfo, $file['tmp_name']);
    finfo_close($finfo);
    if (!in_array($mime, ['image/jpeg', 'image/png'])) {
        header('Location: ../editor-references.php?error=invalid_mime');
        exit;
    }

    // ── 2. AI marker scan ──
    $ai_markers = ['midjourney', 'dalle', 'dall-e', 'stable-diffusion', 'synthetic',
                   'ai-generated', 'generated by ai', 'imagen', 'adobe firefly',
                   'created with ai', 'ai_gen'];
    $fname_lower = strtolower($file['name']);
    $raw_head = file_get_contents($file['tmp_name'], false, null, 0, 8192);
    $ai_detected = false;
    foreach ($ai_markers as $marker) {
        $clean = str_replace([' ', '-'], '', $marker);
        if (strpos(str_replace(['-', '_'], '', $fname_lower), $clean) !== false) {
            $ai_detected = true; break;
        }
        if (stripos($raw_head, $clean) !== false) {
            $ai_detected = true; break;
        }
    }
    if ($ai_detected) {
        header('Location: ../editor-references.php?error=ai_detected');
        exit;
    }

    // ── 3. Open source image (EXIF auto-stripped by GD) ──
    $src_img = ($mime === 'image/png') ? imagecreatefrompng($file['tmp_name']) : imagecreatefromjpeg($file['tmp_name']);
    if (!$src_img) {
        header('Location: ../editor-references.php?error=corrupt');
        exit;
    }

    // ── 4. Resize to 1200px wide ──
    $orig_w = imagesx($src_img);
    $orig_h = imagesy($src_img);
    $target_w = 1200;
    if ($orig_w > $target_w) {
        $target_h = (int)($orig_h * $target_w / $orig_w);
        $resized = imagecreatetruecolor($target_w, $target_h);
        imagecopyresampled($resized, $src_img, 0, 0, 0, 0, $target_w, $target_h, $orig_w, $orig_h);
        imagedestroy($src_img);
        $src_img = $resized;
    }

    // ── 5. SEO filename ──
    $seo_input = $_POST['seo_name'] ?? pathinfo($file['name'], PATHINFO_FILENAME);
    $seo_name = trim(preg_replace('/[^a-zA-Z0-9]+/', '-', $seo_input), '-');
    $seo_name = $seo_name ?: 'exhibition-stand';
    $seo_name = strtolower($seo_name);
    $filename = $seo_name . '.webp';
    $upload_dir = __DIR__ . '/../../assets/img/portfolio';
    if (!is_dir($upload_dir)) mkdir($upload_dir, 0755, true);

    // Prevent duplicate filename
    $counter = 1;
    $base = $seo_name;
    while (file_exists("$upload_dir/$filename")) {
        $filename = $base . '-' . $counter . '.webp';
        $counter++;
    }
    $target = "$upload_dir/$filename";

    // ── 6. Watermark (bottom-right, 30% opacity) ──
    $logo_path = __DIR__ . '/../../assets/img/logo.webp';
    if (file_exists($logo_path)) {
        $logo = imagecreatefromwebp($logo_path);
        if ($logo) {
            $logo_w = imagesx($logo);
            $logo_h = imagesy($logo);
            $img_w = imagesx($src_img);
            $img_h = imagesy($src_img);
            $dst_x = $img_w - $logo_w - 20;
            $dst_y = $img_h - $logo_h - 20;
            imagecopymerge($src_img, $logo, $dst_x, $dst_y, 0, 0, $logo_w, $logo_h, 30);
            imagedestroy($logo);
        }
    }

    // ── 7. Save WEBP ──
    imagewebp($src_img, $target, 85);

    // ── 8. XMP metadata (optional) ──
    $year = $_POST['year'] ?? date('Y');
    $alt_en = $_POST['alt_en'] ?? '';
    @exec(sprintf(
        'exiftool -overwrite_original -q ' .
        '-XMP-dc:Creator="MT Messe Stand" ' .
        '-XMP-dc:Rights="© %s MT Messe Stand. All rights reserved." ' .
        '-XMP-dc:Title="Exhibition Stand Reference - %s" ' .
        '-XMP-dc:Description="%s" ' .
        '-XMP-dc:Subject="exhibition stand, trade fair, portfolio, reference" ' .
        '%s 2>/dev/null',
        escapeshellarg($year),
        escapeshellarg($seo_name),
        escapeshellarg(substr($alt_en, 0, 200)),
        escapeshellarg($target)
    ));

    // ── 9. Steganography (LSB row 0) ──
    $copyright = '© MT Messe Stand ' . $year;
    $img = imagecreatefromwebp($target);
    $w = imagesx($img);
    for ($i = 0; $i < min(strlen($copyright), $w); $i++) {
        $rgb = imagecolorat($img, $i, 0);
        $r = ($rgb >> 16) & 0xFF;
        $g = ($rgb >> 8) & 0xFF;
        $b = $rgb & 0xFF;
        $char = ord($copyright[$i]);
        $r = ($r & 0xFC) | (($char >> 6) & 0x03);
        $g = ($g & 0xFC) | (($char >> 4) & 0x03);
        $b = ($b & 0xFC) | (($char >> 2) & 0x03);
        $new_color = imagecolorallocate($img, $r, $g, $b);
        imagesetpixel($img, $i, 0, $new_color);
    }
    imagewebp($img, $target, 85);
    imagedestroy($img);
    imagedestroy($src_img);

    // ── 10. Update JSON ──
    $json_file = __DIR__ . '/../../data/references.json';
    $fp = fopen($json_file . '.lock', 'w');
    flock($fp, LOCK_EX);
    $refs = file_exists($json_file) ? json_decode(file_get_contents($json_file), true) : [];
    if (!is_array($refs)) $refs = [];
    $max_pos = 0;
    foreach ($refs as $r) $max_pos = max($max_pos, $r['position'] ?? 0);
    $entry = [
        'position'     => $max_pos + 1,
        'filename'     => $filename,
        'src'          => '/assets/img/portfolio/' . $filename,
        'sector'       => $_POST['sector'] ?? '',
        'fair'         => $_POST['fair'] ?? '',
        'city'         => $_POST['city'] ?? '',
        'country'      => $_POST['country'] ?? '',
        'year'         => $year,
        'alt_en'       => $_POST['alt_en'] ?? '',
        'alt_tr'       => $_POST['alt_tr'] ?? '',
        'alt_de'       => $_POST['alt_de'] ?? '',
        'alt_fr'       => $_POST['alt_fr'] ?? '',
        'alt_es'       => $_POST['alt_es'] ?? '',
        'alt_ru'       => $_POST['alt_ru'] ?? '',
        'alt_zh'       => $_POST['alt_zh'] ?? '',
        'alt_ar'       => $_POST['alt_ar'] ?? '',
        'watermarked'  => true,
        'stegano_hash' => md5($copyright),
    ];
    $refs[] = $entry;
    $tmp = $json_file . '.tmp';
    file_put_contents($tmp, json_encode($refs, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    rename($tmp, $json_file);
    flock($fp, LOCK_UN);
    fclose($fp);
    @unlink($json_file . '.lock');

    // ── 11. Regenerate sitemap ──
    require_once __DIR__ . '/../../templates/sitemap-generator.php';
    generate_references_sitemap();

    log_action('upload_reference', 'success', ['file' => $filename]);
    header('Location: ../editor-references.php?uploaded=1');

} catch (Throwable $e) {
    log_error('Upload reference: ' . $e->getMessage());
    header('Location: ../editor-references.php?error=system_error');
}
